### ISSUE TITLE
Automated test after installation

### ISSUE THREAD

**Issue by MiniPlayer** [Hurence/historian#171] opened 2020-09-08 09:54 UTC
The REST api is already tested with integration test. 
We want to add other test after the historian has been installed in standalone mode.
The test could test some curl command and ensure the result is as expected.
Should be done after issue #170

**Comment by lhubert** [comment] 2020-09-08 10:51
We should retest it here since this test is about automating what we have in the user guide (and all guides) and see if we have a **regression** between what is documented and what we have coded in the new release. So we will do the curl to verify this. We won't see the regression versus the docs in the integration tests (we have never seen them). Here we will see them. We will automate the queries given as examples in all our docs.  And at last our docs will be in sync with our code (which is never the case).

**Comment by MiniPlayer** [comment] 2020-09-08 12:45
I think we need to isolate queries and expected response in separate files from the docs.
And then includes those files in the doc. This way we could test those queries but then the ones that writes the docs should have to do this properly when adding other queries.

Another way would be to create a "Tag" or an "Annotation" in the doc where we want a query and response to be tested. But that seems more complicated to me.

**Comment by MiniPlayer** [comment] 2020-09-08 12:46
Initially I wanted the doc to be automatically generated so that we can test what we generate. But this would take too much time to settle in my opinion.

**Closed** 2021-02-01 16:14 UTC
Labels: tests
